# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FleetTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FleetTracker

  target 'FleetTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FleetTrackerUITests' do
    # Pods for testing
  end

pod "FGRoute"

end
